language: node_js
node_js: 
script:
  - yarn build
before_install:
- openssl aes-256-cbc -K $encrypted_95036e2191f1_key -iv $encrypted_95036e2191f1_iv
  -in LightsailDefaultKey-ap-south-1.pem.enc -out /tmp/LightsailDefaultKey-ap-south-1.pem
  -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
deploy:
  provider: script
  script: scp -o stricthostkeychecking=no -rp $TRAVIS_BUILD_DIR/build bitnami@52.66.162.168:~/test

